# Тег версии.
version: "3.0"

# Сервис = контейнер.
# Сервисом может быть клиент, сервер, сервер баз данных...
services:
  # Основное приложение
  learning_log:

    container_name: learning_log

    # Собственный образ. Создаётся в соответствии с инструкцией "build".
    # Имя образа выбирается произвольно.
    image: learning_log

    # параметры сборки образа
    build:
      context: .  # из корневого каталога проекта
      dockerfile: Dockerfile

    ports:
      - "80:80"

    networks:
      - custom

# Сетевое взаимодействие между контейнерами
networks:
  # Имя сети
  custom:
    # Выбор варианта организации сети.
    # Bridge - создаётся внутренняя скрытая сеть.
    # Можно указать IP-адрес и подсеть. Без указания Docker выбирает следующую
    # подсеть, доступную в пространстве приватных IP-адресов.
    driver: bridge
